http.host: 0.0.0.0
log.level: info
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.workers: 2
xpack.monitoring.elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.elasticsearch.password: quantum_elastic_2026
xpack.monitoring.elasticsearch.username: elastic
